language: php

matrix:
    include:
        - php: 7.1
        - php: 7.0
        - php: 5.6
        - php: 5.5
        - php: 5.4
    fast_finish: true

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

before_install:
    - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi

install:
    - composer self-update

before_script:
    - composer install --prefer-dist --no-interaction

script:
    - vendor/bin/parallel-lint src
    - vendor/bin/phpunit --bootstrap vendor/autoload.php tests
